import os
import yaml

rules_dir = "rules"
os.makedirs(rules_dir, exist_ok=True)

# Список из 45 правил для генерации
rules = [
    {"id": "API4-2023-RATE-001", "name": "Unrestricted Resource Consumption", "severity": "medium", "owasp": "API4:2023", "cwe": 770, "description": "Проверка отсутствия ограничения частоты запросов", "conditions": [{"type": "rate_limit", "requests_count": 100, "time_window": 10, "expected_status": 429}], "recommendation": "Внедрить ограничение частоты запросов (Rate Limiting)"},
    {"id": "API8-2023-HEADERS-001", "name": "Missing Security Headers", "severity": "medium", "owasp": "API8:2023", "cwe": 693, "description": "Проверка наличия обязательных заголовков безопасности", "conditions": [{"type": "missing_headers", "headers": ["Strict-Transport-Security", "X-Frame-Options", "X-Content-Type-Options", "Content-Security-Policy"]}], "recommendation": "Настроить отдачу заголовков безопасности на уровне веб-сервера"},
    {"id": "API8-2023-HTTPS-001", "name": "Missing HTTPS Enforcement", "severity": "high", "owasp": "API8:2023", "cwe": 319, "description": "Проверка принудительного использования HTTPS", "conditions": [{"type": "https_enforcement", "expected_redirect": True}], "recommendation": "Настроить редирект всех HTTP-запросов на HTTPS"},
    {"id": "API2-2023-JWT-ALG-001", "name": "Weak JWT Algorithm", "severity": "high", "owasp": "API2:2023", "cwe": 327, "description": "Проверка использования уязвимых алгоритмов JWT", "conditions": [{"type": "jwt_algorithm", "test_algorithms": ["none", "HS256"], "expected_status": [401, 403]}], "recommendation": "Использовать только безопасные алгоритмы (RS256, ES256)"},
    {"id": "API8-2023-SQLI-001", "name": "SQL Injection in Parameters", "severity": "critical", "owasp": "API8:2023", "cwe": 89, "description": "Проверка параметров на уязвимость к SQL-инъекциям", "conditions": [{"type": "sql_injection", "payloads": ["' OR '1'='1", "'; DROP TABLE users--", "1 UNION SELECT NULL--"], "expected_status": [500, 400]}], "recommendation": "Использовать параметризованные запросы и ORM"},
    {"id": "API8-2023-XSS-001", "name": "Reflected XSS in API Response", "severity": "high", "owasp": "API8:2023", "cwe": 79, "description": "Проверка параметров на отражение XSS-пейлоадов", "conditions": [{"type": "xss_reflected", "payloads": ["<script>alert(1)</script>", "<img src=x onerror=alert(1)>"], "check_response": True}], "recommendation": "Экранировать все пользовательские данные в ответах API"},
    {"id": "API7-2023-SSRF-001", "name": "Server-Side Request Forgery (SSRF)", "severity": "critical", "owasp": "API7:2023", "cwe": 918, "description": "Проверка параметров URL на SSRF", "conditions": [{"type": "ssrf", "payloads": ["http://127.0.0.1:80", "http://localhost:22", "http://169.254.169.254/latest/meta-data/"], "expected_status": [400, 403, 500]}], "recommendation": "Валидировать и очищать все URL, использовать whitelist доменов"},
    {"id": "API8-2023-TRAVERSAL-001", "name": "Path Traversal", "severity": "high", "owasp": "API8:2023", "cwe": 22, "description": "Проверка параметров на Directory Traversal", "conditions": [{"type": "path_traversal", "payloads": ["../../../etc/passwd", "..\\..\\windows\\system32\\config\\sam"], "expected_status": [400, 403, 500]}], "recommendation": "Валидировать пути, использовать базовую директорию (chroot)"},
    {"id": "API8-2023-VERBOSE-001", "name": "Verbose Error Messages", "severity": "low", "owasp": "API8:2023", "cwe": 209, "description": "Проверка на раскрытие stack trace в ошибках", "conditions": [{"type": "verbose_errors", "trigger_payload": "invalid_json{{{", "check_patterns": ["Traceback", "Exception", "Stack trace", "SQLSTATE"]}], "recommendation": "Возвращать общие сообщения об ошибках, логировать детали на сервере"},
    {"id": "API8-2023-METHODS-001", "name": "Unsafe HTTP Methods", "severity": "medium", "owasp": "API8:2023", "cwe": 650, "description": "Проверка поддержки небезопасных HTTP методов", "conditions": [{"type": "http_methods", "methods": ["TRACE", "PUT", "DELETE"], "expected_status": [405, 501]}], "recommendation": "Отключить ненужные HTTP методы на уровне веб-сервера"},
    {"id": "API8-2023-CORS-001", "name": "CORS Misconfiguration", "severity": "high", "owasp": "API8:2023", "cwe": 942, "description": "Проверка на слишком разрешительную CORS политику", "conditions": [{"type": "cors", "origin": "https://evil.com", "check_header": "Access-Control-Allow-Origin", "expected_value": "*"}], "recommendation": "Настроить строгий whitelist доменов в CORS"},
    {"id": "API8-2023-COOKIES-001", "name": "Insecure Cookie Flags", "severity": "medium", "owasp": "API8:2023", "cwe": 614, "description": "Проверка флагов Secure и HttpOnly у cookies", "conditions": [{"type": "cookie_flags", "check_flags": ["Secure", "HttpOnly", "SameSite"]}], "recommendation": "Устанавливать флаги Secure, HttpOnly и SameSite=Strict для всех cookies"},
    {"id": "API8-2023-INFO-001", "name": "Server Information Disclosure", "severity": "low", "owasp": "API8:2023", "cwe": 200, "description": "Проверка на раскрытие версии сервера в заголовках", "conditions": [{"type": "info_disclosure", "headers": ["Server", "X-Powered-By", "X-AspNet-Version"]}], "recommendation": "Скрыть или изменить заголовки, раскрывающие информацию о сервере"},
    {"id": "API2-2023-BRUTE-001", "name": "Brute Force Protection", "severity": "high", "owasp": "API2:2023", "cwe": 307, "description": "Проверка защиты от перебора паролей", "conditions": [{"type": "brute_force", "endpoint": "/login", "attempts": 10, "expected_status": 429}], "recommendation": "Внедрить ограничение попыток входа и CAPTCHA"},
    {"id": "API5-2023-NO-AUTH-001", "name": "Missing Authentication", "severity": "critical", "owasp": "API5:2023", "cwe": 306, "description": "Проверка доступа к защищенным эндпоинтам без токена", "conditions": [{"type": "missing_auth", "expected_status": [401, 403]}], "recommendation": "Требовать аутентификацию для всех защищенных эндпоинтов"},
    {"id": "API3-2023-SENSITIVE-URL-001", "name": "Sensitive Data in URL", "severity": "medium", "owasp": "API3:2023", "cwe": 598, "description": "Проверка передачи чувствительных данных через GET-параметры", "conditions": [{"type": "sensitive_url", "check_params": ["password", "token", "secret", "api_key"]}], "recommendation": "Передавать чувствительные данные только в теле запроса (POST) или заголовках"},
    {"id": "API6-2023-MASS-ASSIGN-002", "name": "Mass Assignment in PUT/PATCH", "severity": "high", "owasp": "API6:2023", "cwe": 915, "description": "Проверка возможности изменения скрытых полей через PUT/PATCH", "conditions": [{"type": "mass_assignment", "fields": ["isAdmin", "role", "balance", "permissions"], "expected_status": [200, 400]}], "recommendation": "Использовать DTO и явно указывать разрешенные поля для обновления"},
    {"id": "API3-2023-EXCESSIVE-002", "name": "Excessive Data in List Endpoints", "severity": "medium", "owasp": "API3:2023", "cwe": 200, "description": "Проверка на раскрытие лишних данных в списках объектов", "conditions": [{"type": "excessive_data_list", "sensitive_fields": ["password", "salt", "secret", "internal_id"]}], "recommendation": "Возвращать только необходимые поля, использовать пагинацию"},
    {"id": "API1-2023-IDOR-001", "name": "IDOR in API Parameters", "severity": "critical", "owasp": "API1:2023", "cwe": 639, "description": "Проверка на IDOR через подмену ID в параметрах запроса", "conditions": [{"type": "idor_param", "param_name": "user_id", "test_values": ["1", "999999"], "expected_status": [403, 404]}], "recommendation": "Проверять права доступа к объекту для текущего пользователя"},
    {"id": "API8-2023-REDIRECT-001", "name": "Open Redirect", "severity": "medium", "owasp": "API8:2023", "cwe": 601, "description": "Проверка параметров на возможность открытого редиректа", "conditions": [{"type": "open_redirect", "payloads": ["https://evil.com", "//evil.com"], "check_header": "Location"}], "recommendation": "Валидировать URL для редиректа, использовать whitelist доменов"},
    {"id": "API8-2023-CSRF-001", "name": "Missing CSRF Protection", "severity": "medium", "owasp": "API8:2023", "cwe": 352, "description": "Проверка наличия CSRF-токенов для изменяющих запросов", "conditions": [{"type": "csrf", "methods": ["POST", "PUT", "DELETE"], "check_header": "X-CSRF-Token"}], "recommendation": "Требовать CSRF-токен для всех изменяющих состояние запросов"},
    {"id": "API9-2023-INV-001", "name": "Deprecated Endpoints Active", "severity": "low", "owasp": "API9:2023", "cwe": 1104, "description": "Проверка на использование устаревших версий API", "conditions": [{"type": "deprecated_api", "versions": ["v1", "beta", "alpha"], "expected_status": [410, 404]}], "recommendation": "Отключать устаревшие версии API и использовать версионирование"},
    {"id": "API10-2023-CONSUME-001", "name": "Unsafe Third-Party API Consumption", "severity": "medium", "owasp": "API10:2023", "cwe": 829, "description": "Проверка доверия к данным от внешних API", "conditions": [{"type": "unsafe_consumption", "check_validation": True}], "recommendation": "Валидировать и очищать все данные, полученные от сторонних API"},
    {"id": "API4-2023-PAYLOAD-001", "name": "Large Payload Size (DoS)", "severity": "medium", "owasp": "API4:2023", "cwe": 400, "description": "Проверка ограничения размера тела запроса", "conditions": [{"type": "large_payload", "size_mb": 50, "expected_status": 413}], "recommendation": "Ограничить максимальный размер тела запроса на уровне веб-сервера"},
    {"id": "API8-2023-CONTENT-TYPE-001", "name": "Improper Content Type Validation", "severity": "medium", "owasp": "API8:2023", "cwe": 436, "description": "Проверка строгой валидации Content-Type", "conditions": [{"type": "content_type", "expected_type": "application/json", "test_type": "application/xml", "expected_status": 415}], "recommendation": "Строго проверять Content-Type и отклонять неподдерживаемые типы"},
    {"id": "API2-2023-SESSION-001", "name": "Session Fixation", "severity": "high", "owasp": "API2:2023", "cwe": 384, "description": "Проверка на изменение сессионного токена после логина", "conditions": [{"type": "session_fixation", "check_token_change": True}], "recommendation": "Генерировать новый сессионный токен после успешной аутентификации"},
    {"id": "API2-2023-PASSWORD-001", "name": "Weak Password Policy", "severity": "medium", "owasp": "API2:2023", "cwe": 521, "description": "Проверка требований к сложности пароля", "conditions": [{"type": "weak_password", "test_passwords": ["123456", "password", "qwerty"], "expected_status": 400}], "recommendation": "Требовать сложные пароли и проверять их по базам утечек"},
    {"id": "API8-2023-CMD-001", "name": "Command Injection", "severity": "critical", "owasp": "API8:2023", "cwe": 78, "description": "Проверка параметров на внедрение команд ОС", "conditions": [{"type": "command_injection", "payloads": ["; ls -la", "| cat /etc/passwd", "`whoami`"], "expected_status": [400, 500]}], "recommendation": "Никогда не передавать пользовательский ввод в системные команды"},
    {"id": "API8-2023-XXE-001", "name": "XML External Entity (XXE)", "severity": "critical", "owasp": "API8:2023", "cwe": 611, "description": "Проверка XML-парсера на уязвимость к XXE", "conditions": [{"type": "xxe", "payload": '<?xml version="1.0" ?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><root>&xxe;</root>', "expected_status": [400, 500]}], "recommendation": "Отключить обработку внешних сущностей в XML-парсерах"},
    {"id": "API8-2023-HSTS-001", "name": "Missing HSTS Header", "severity": "medium", "owasp": "API8:2023", "cwe": 523, "description": "Проверка наличия заголовка Strict-Transport-Security", "conditions": [{"type": "hsts", "check_header": "Strict-Transport-Security", "expected_pattern": "max-age="}], "recommendation": "Добавить заголовок Strict-Transport-Security с достаточным max-age"},
    {"id": "API8-2023-CSP-001", "name": "Missing Content Security Policy", "severity": "medium", "owasp": "API8:2023", "cwe": 693, "description": "Проверка наличия заголовка Content-Security-Policy", "conditions": [{"type": "csp", "check_header": "Content-Security-Policy"}], "recommendation": "Внедрить строгую политику Content-Security-Policy"},
    {"id": "API3-2023-BASE64-001", "name": "Sensitive Data in Base64", "severity": "high", "owasp": "API3:2023", "cwe": 319, "description": "Проверка на передачу чувствительных данных в Base64", "conditions": [{"type": "base64_data", "check_decoding": True}], "recommendation": "Шифровать чувствительные данные, Base64 не является шифрованием"},
    {"id": "API8-2023-RACE-001", "name": "Race Condition", "severity": "high", "owasp": "API8:2023", "cwe": 362, "description": "Проверка на уязвимость к гонкам (Race Condition)", "conditions": [{"type": "race_condition", "concurrent_requests": 10, "check_balance": True}], "recommendation": "Использовать транзакции и блокировки для критических операций"},
    {"id": "API8-2023-GRAPHQL-INT-001", "name": "GraphQL Introspection Enabled", "severity": "medium", "owasp": "API8:2023", "cwe": 200, "description": "Проверка включенной интроспекции GraphQL", "conditions": [{"type": "graphql_introspection", "query": '{ "__schema": { "types": { "name" } } }', "expected_status": [400, 403]}], "recommendation": "Отключить интроспекцию GraphQL в продуктивной среде"},
    {"id": "API4-2023-GRAPHQL-DEPTH-001", "name": "GraphQL Query Depth Limit", "severity": "medium", "owasp": "API4:2023", "cwe": 770, "description": "Проверка ограничения глубины запросов GraphQL", "conditions": [{"type": "graphql_depth", "depth": 20, "expected_status": 400}], "recommendation": "Ограничить максимальную глубину и сложность запросов GraphQL"},
    {"id": "API2-2023-API-KEY-001", "name": "API Key in URL", "severity": "high", "owasp": "API2:2023", "cwe": 598, "description": "Проверка передачи API-ключей в URL", "conditions": [{"type": "api_key_url", "check_params": ["api_key", "apikey", "token"]}], "recommendation": "Передавать API-ключи только в заголовках (например, X-API-Key)"},
    {"id": "API8-2023-REDIRECT-002", "name": "Unvalidated Redirects and Forwards", "severity": "medium", "owasp": "API8:2023", "cwe": 601, "description": "Проверка на невалидированные редиректы", "conditions": [{"type": "unvalidated_redirect", "payloads": ["https://malicious.com"], "check_header": "Location"}], "recommendation": "Валидировать все URL для редиректов"},
    {"id": "API8-2023-JSON-001", "name": "JSON Injection", "severity": "medium", "owasp": "API8:2023", "cwe": 830, "description": "Проверка на уязвимость к JSON-инъекциям", "conditions": [{"type": "json_injection", "payloads": ['{"user": "admin", "role": "admin"}'], "expected_status": [400, 500]}], "recommendation": "Строго валидировать структуру JSON-запросов"},
    {"id": "API8-2023-DEBUG-001", "name": "Debug Mode Enabled", "severity": "high", "owasp": "API8:2023", "cwe": 489, "description": "Проверка на включенный режим отладки", "conditions": [{"type": "debug_mode", "check_patterns": ["DEBUG", "Traceback", "Werkzeug", "Django"]}], "recommendation": "Отключить режим отладки в продуктивной среде"},
    {"id": "API8-2023-STATE-001", "name": "Improper State Management", "severity": "medium", "owasp": "API8:2023", "cwe": 538, "description": "Проверка корректности управления состоянием API", "conditions": [{"type": "state_management", "check_sequence": True}], "recommendation": "Реализовать корректное управление состоянием сессий и транзакций"},
    {"id": "API2-2023-JWT-EXP-001", "name": "JWT Missing Expiration", "severity": "high", "owasp": "API2:2023", "cwe": 613, "description": "Проверка наличия срока действия у JWT токена", "conditions": [{"type": "jwt_expiration", "check_claim": "exp"}], "recommendation": "Всегда устанавливать и проверять срок действия (exp) JWT токенов"},
    {"id": "API1-2023-BOLA-002", "name": "BOLA in Query Params", "severity": "critical", "owasp": "API1:2023", "cwe": 639, "description": "Проверка на BOLA через подмену ID в query-параметрах", "conditions": [{"type": "bola", "param_name": "id", "test_values": ["1", "999999"], "expected_status": [403, 404]}], "recommendation": "Проверять права доступа к объекту для текущего пользователя"},
    {"id": "API3-2023-EXCESSIVE-003", "name": "Excessive Data in Headers", "severity": "medium", "owasp": "API3:2023", "cwe": 200, "description": "Проверка на раскрытие чувствительных данных в заголовках ответа", "conditions": [{"type": "excessive_data_headers", "check_headers": ["X-User-Password", "X-Internal-Token"]}], "recommendation": "Не передавать чувствительные данные в заголовках HTTP"},
    {"id": "API8-2023-CLICKJACK-001", "name": "Missing X-Frame-Options", "severity": "medium", "owasp": "API8:2023", "cwe": 1021, "description": "Проверка наличия заголовка защиты от кликджекинга", "conditions": [{"type": "clickjacking", "check_header": "X-Frame-Options"}], "recommendation": "Добавить заголовок X-Frame-Options: DENY или SAMEORIGIN"},
    {"id": "API8-2023-SNIFF-001", "name": "Missing X-Content-Type-Options", "severity": "low", "owasp": "API8:2023", "cwe": 16, "description": "Проверка наличия заголовка защиты от MIME-sniffing", "conditions": [{"type": "mime_sniffing", "check_header": "X-Content-Type-Options", "expected_value": "nosniff"}], "recommendation": "Добавить заголовок X-Content-Type-Options: nosniff"}
]

for rule in rules:
    filename = f"{rules_dir}/{rule['id'].lower().replace(':', '_').replace('-', '_')}.yaml"
    with open(filename, 'w', encoding='utf-8') as f:
        yaml.dump(rule, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
    print(f"✅ Создан {filename}")

print(f"\n🎉 Успешно сгенерировано {len(rules)} правил в папке {rules_dir}/")
