import json
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import os

# Регистрируем шрифт с поддержкой кириллицы
font_path = '/System/Library/Fonts/Supplemental/Arial Unicode.ttf'
if os.path.exists(font_path):
    pdfmetrics.registerFont(TTFont('ArialUnicode', font_path))
    FONT_NAME = 'ArialUnicode'
else:
    FONT_NAME = 'Helvetica'

def export_json(results, filepath):
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

def export_html(results, filepath):
    html = "<html><head><meta charset='utf-8'></head><body>"
    html += f"<h1>API Security Report</h1><p>Date: {datetime.now().strftime('%d.%m.%Y %H:%M')}</p>"
    if not results:
        html += "<p>No vulnerabilities found.</p>"
    else:
        html += "<table border='1' cellpadding='5'><tr><th>ID</th><th>Severity</th><th>Description</th></tr>"
        for r in results:
            html += f"<tr><td>{r.get('id', '—')}</td><td>{r.get('severity', 'unknown')}</td><td>{r.get('description', '—')}</td></tr>"
        html += "</table>"
    html += "<p>Generated by API Security Scanner v1.0</p></body></html>"
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html)

def export_pdf(results, filepath):
    doc = SimpleDocTemplate(filepath, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    # Стили
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontName=FONT_NAME,
        fontSize=16,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#1a237e'),
        spaceAfter=12
    )
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontName=FONT_NAME,
        fontSize=14,
        spaceAfter=8,
        textColor=colors.HexColor('#283593')
    )
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontName=FONT_NAME,
        fontSize=10,
        leading=13
    )
    cell_style = ParagraphStyle(
        'CellStyle',
        parent=styles['BodyText'],
        fontName=FONT_NAME,
        fontSize=9,
        leading=12,
        alignment=TA_JUSTIFY,   # Выравнивание по ширине
        leftIndent=4,
        rightIndent=4
    )

    story = []

    story.append(Paragraph("API Security Report", title_style))
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%d.%m.%Y %H:%M')}", body_style))
    if results:
        story.append(Paragraph(f"Total vulnerabilities found: {len(results)}", body_style))
    story.append(Spacer(1, 0.5*cm))

    if not results:
        story.append(Paragraph("No vulnerabilities found.", body_style))
    else:
        story.append(Paragraph("List of found vulnerabilities:", heading_style))
        story.append(Spacer(1, 0.3*cm))

        # Данные для таблицы
        data = [["ID", "Severity", "Description"]]
        for r in results:
            # Передаём текст в Paragraph для использования стиля cell_style
            desc_para = Paragraph(r.get('description', '—'), cell_style)
            data.append([
                Paragraph(str(r.get('id', '—')), cell_style),
                Paragraph(r.get('severity', 'unknown'), cell_style),
                desc_para
            ])

        # Ширина колонок: ID 1.5 см, Severity 3 см, Description – остаток (None = auto)
        table = Table(data, colWidths=[1.5*cm, 3*cm, None])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#283593')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,-1), FONT_NAME),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('BOTTOMPADDING', (0,0), (-1,0), 8),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,1), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 4),
            ('RIGHTPADDING', (0,0), (-1,-1), 4),
            ('BACKGROUND', (0,1), (-1,-1), colors.beige),
            ('GRID', (0,0), (-1,-1), 1, colors.grey),  # Толщина границ 1 pt
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('WORD_WRAP', (0,0), (-1,-1), True),
        ]))
        story.append(table)

    doc.build(story)
